-- AlterEnum
ALTER TYPE "ProjectStatus" ADD VALUE 'NOT_STARTED';

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "goalCompletedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'INBOX',
ALTER COLUMN "priority" SET DEFAULT 'LOW';
